#!/usr/bin/env bash

set -euo pipefail

flags=(
    "-ferror-limit=1"
    "-ffast-math"
    "-flto"
    "-fno-autolink"
    "-fno-exceptions"
    "-fno-math-errno"
    "-fno-rtti"
    "-fno-unwind-tables"
    "-fshort-enums"
    "-g"
    "-march=native"
    "-nostdlib++"
    "-O3"
    "-pthread"
    "-std=gnu++11"
    "-Werror"
    "-Weverything"
    "-Wno-c++98-compat"
    "-Wno-c++98-compat-pedantic"
    "-Wno-c99-extensions"
    "-Wno-padded"
    "-Wno-reserved-id-macro"
)

now () {
    date +%s.%N
}

(
    start=$(now)
    clang-format -i -verbose "$WD/src"/*
    mold -run clang++ -o "$WD/bin/main" "${flags[@]}" "$WD/src/main.cpp"
    end=$(now)
    python3 -c "print(\"Compiled! ({:.3f}s)\n\".format($end - $start))"
)

"$WD/bin/main" "$WD/out/main.bmp"
