#!/usr/bin/env bash

set -euo pipefail

target="$WD/bin/main"
flags=(
    "-fanalyzer"
    "-fno-exceptions"
    "-fno-rtti"
    "-fno-unwind-tables"
    "-fshort-enums"
    "-fsingle-precision-constant"
    "-march=native"
    "-O3"
    "-std=gnu++11"
    "-Wall"
    "-Wcast-align"
    "-Wcast-align=strict"
    "-Wcast-qual"
    "-Wconversion"
    "-Wdate-time"
    "-Wdouble-promotion"
    "-Wduplicated-branches"
    "-Wduplicated-cond"
    "-Werror"
    "-Wextra"
    "-Wfatal-errors"
    "-Wfloat-equal"
    "-Wformat-signedness"
    "-Wformat=2"
    "-Winline"
    "-Wlogical-op"
    "-Wmissing-declarations"
    "-Wmissing-include-dirs"
    "-Wnull-dereference"
    "-Wpacked"
    "-Wpedantic"
    "-Wpointer-arith"
    "-Wredundant-decls"
    "-Wshadow"
    "-Wstack-protector"
    "-Wswitch-enum"
    "-Wtrampolines"
    "-Wundef"
    "-Wunused"
    "-Wunused-macros"
    "-Wwrite-strings"
)
files=(
    main.cpp
)

now () {
    date +%s.%N
}

cppcheck \
    --enable=all \
    --suppress=cstyleCast \
    --suppress=missingIncludeSystem \
    --suppress=resourceLeak \
    "$WD/src" \
    | sed 's/\/.*\/\(.*\) \.\.\./\1/g'
clang-format -i -verbose "$WD/src"/* 2>&1 | sed 's/\/.*\///g'
(
    start=$(now)
    cp "$WD/src"/* "$WD/build"
    cd "$WD/build"
    g++ -static -g -o "$target" "${flags[@]}" "${files[@]}"
    end=$(now)
    python3 -c "print(\"Compiled! ({:.3f}s)\n\".format(${end} - ${start}))"
)
"$target" "$WD/out/main.bmp"
